# vim:set ft=tmux:
%hidden MODULE_NAME='spotify'

# Set the icon (using the Spotify Nerd Font icon)
set -ogq "@catppuccin_${MODULE_NAME}_icon" " "

# Set the color (Catppuccin Green)
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"

# Set the text using spotify-tmux variables
# #{spotify_status} gives play/pause icon, #{spotify_artist} and #{spotify_track} for info
set -ogq "@catppuccin_${MODULE_NAME}_text" " #{l:#{spotify_state}#{spotify_artist} - #{spotify_track}}"

source -F '#{d:current_file}/../plugins/tmux/utils/status_module.conf'

